services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel_network

  php:
    build:
      context: ./docker/php
    container_name: laravel_php
    volumes:
      - ./:/var/www/html
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - postgres
    networks:
      - laravel_network

  node10:
    image: node:18
    tty: true
    working_dir: /home/node
    volumes:
      - ./:/home/node
    ports:
      - "5173:5173"
    networks:
      - laravel_network

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: laravel_blog
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel_network

  redis:
    image: redis:8-alpine
    restart: always
    ports:
      - '6379:6379'
    # not for production
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
    networks:
      - laravel_network

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - laravel_network

  mailhog:
    image: mailhog/mailhog:latest
    environment:
      - MH_STORAGE=maildir
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI
    networks:
      - laravel_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus # Persistent storage for Prometheus data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090" # Prometheus UI
    networks:
      - laravel_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin # CHANGE THIS IN PRODUCTION!
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning # For provisioning datasources/dashboards
      - grafana_data:/var/lib/grafana # Persistent storage for Grafana data
    ports:
      - "3000:3000" # Grafana UI
    depends_on:
      - prometheus # Ensure Prometheus is up before Grafana
    networks:
      - laravel_network


volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
  cache:
    driver: local

networks:
  laravel_network:
    driver: bridge